"""add_conversation_models

Revision ID: 076a5b5c57a8
Revises: 293ab849a560
Create Date: 2025-08-29 04:02:16.410749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '076a5b5c57a8'
down_revision = '293ab849a560'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Check if tables already exist (in case Business/Enterprise created them)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    # Skip if conversation tables already exist
    if 'conversation_intents' in existing_tables:
        print("Conversation tables already exist, skipping creation...")
        return

    op.create_table('conversation_intents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_params', sa.JSON(), nullable=False),
    sa.Column('optional_params', sa.JSON(), nullable=False),
    sa.Column('example_phrases', sa.JSON(), nullable=False),
    sa.Column('clarification_questions', sa.JSON(), nullable=False),
    sa.Column('service_endpoint', sa.String(length=200), nullable=True),
    sa.Column('action_template', sa.JSON(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_intents_name'), 'conversation_intents', ['name'], unique=True)
    op.create_table('conversation_patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_hash', sa.String(length=64), nullable=False),
    sa.Column('pattern_type', sa.String(length=50), nullable=False),
    sa.Column('conversation_flow', sa.JSON(), nullable=False),
    sa.Column('success_criteria', sa.JSON(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('average_turns', sa.Float(), nullable=False),
    sa.Column('average_duration_seconds', sa.Float(), nullable=False),
    sa.Column('first_seen', sa.DateTime(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('is_promoted', sa.Boolean(), nullable=False),
    sa.Column('promoted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_patterns_pattern_hash'), 'conversation_patterns', ['pattern_hash'], unique=True)
    op.create_table('conversation_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_activity', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.Column('extracted_params', sa.JSON(), nullable=False),
    sa.Column('primary_intent', sa.String(length=100), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('session_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_human', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_sessions_primary_intent'), 'conversation_sessions', ['primary_intent'], unique=False)
    op.create_index(op.f('ix_conversation_sessions_user_id'), 'conversation_sessions', ['user_id'], unique=False)
    op.create_table('conversation_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_params', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('pod_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_actions_session_id'), 'conversation_actions', ['session_id'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_config', sa.JSON(), nullable=False),
    sa.Column('suggested_actions', sa.JSON(), nullable=False),
    sa.Column('detected_intent', sa.String(length=100), nullable=True),
    sa.Column('intent_confidence', sa.Float(), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('llm_model_used', sa.String(length=100), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['conversation_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_messages_session_id'), 'conversation_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_conversation_messages_timestamp'), 'conversation_messages', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversation_messages_timestamp'), table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_session_id'), table_name='conversation_messages')
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_conversation_actions_session_id'), table_name='conversation_actions')
    op.drop_table('conversation_actions')
    op.drop_index(op.f('ix_conversation_sessions_user_id'), table_name='conversation_sessions')
    op.drop_index(op.f('ix_conversation_sessions_primary_intent'), table_name='conversation_sessions')
    op.drop_table('conversation_sessions')
    op.drop_index(op.f('ix_conversation_patterns_pattern_hash'), table_name='conversation_patterns')
    op.drop_table('conversation_patterns')
    op.drop_index(op.f('ix_conversation_intents_name'), table_name='conversation_intents')
    op.drop_table('conversation_intents')
    # ### end Alembic commands ###