"""initial_community_tables

Revision ID: 293ab849a560
Revises: 
Create Date: 2025-08-11 19:35:59.065292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '293ab849a560'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Check if tables already exist (in case Business/Enterprise created them)
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()
    
    # Skip if key tables already exist (meaning another edition ran first)
    if 'adapters' in existing_tables:
        print("Community tables already exist, skipping creation...")
        return
    
    op.create_table('adapters',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('min_edition', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('installed', sa.Boolean(), nullable=False),
    sa.Column('install_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_usage_metrics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('workflow_count', sa.Integer(), nullable=True),
    sa.Column('adapter_count', sa.Integer(), nullable=True),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('api_calls_month', sa.Integer(), nullable=True),
    sa.Column('storage_bytes', sa.Integer(), nullable=True),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_tenant_period', 'basic_usage_metrics', ['tenant_id', 'period_start'], unique=False)
    op.create_table('billing_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_event_id')
    )
    op.create_index('idx_billing_events_tenant', 'billing_events', ['tenant_id'], unique=False)
    op.create_index('idx_billing_events_type', 'billing_events', ['event_type'], unique=False)
    op.create_table('bridge_connections',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_lineage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=True),
    sa.Column('source_node_id', sa.UUID(), nullable=True),
    sa.Column('target_node_id', sa.UUID(), nullable=True),
    sa.Column('transformation_type', sa.String(length=100), nullable=True),
    sa.Column('transformation_details', sa.JSON(), nullable=True),
    sa.Column('data_snapshot_before', sa.JSON(), nullable=True),
    sa.Column('data_snapshot_after', sa.JSON(), nullable=True),
    sa.Column('quality_impact', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lineage_nodes', 'data_lineage', ['source_node_id', 'target_node_id'], unique=False)
    op.create_index('idx_lineage_time', 'data_lineage', ['timestamp'], unique=False)
    op.create_index('idx_lineage_workflow', 'data_lineage', ['workflow_instance_id'], unique=False)
    op.create_index(op.f('ix_data_lineage_timestamp'), 'data_lineage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_data_lineage_workflow_instance_id'), 'data_lineage', ['workflow_instance_id'], unique=False)
    op.create_table('data_quality_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_instance_id', sa.UUID(), nullable=True),
    sa.Column('node_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('data_reference', sa.String(length=500), nullable=True),
    sa.Column('assessment_time', sa.DateTime(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('dimension_scores', sa.JSON(), nullable=True),
    sa.Column('issues_found', sa.JSON(), nullable=True),
    sa.Column('suggestions', sa.JSON(), nullable=True),
    sa.Column('data_profile', sa.JSON(), nullable=True),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_quality_tenant', 'data_quality_assessments', ['tenant_id'], unique=False)
    op.create_index('idx_quality_time', 'data_quality_assessments', ['assessment_time'], unique=False)
    op.create_index('idx_quality_workflow', 'data_quality_assessments', ['workflow_instance_id'], unique=False)
    op.create_index(op.f('ix_data_quality_assessments_assessment_time'), 'data_quality_assessments', ['assessment_time'], unique=False)
    op.create_index(op.f('ix_data_quality_assessments_tenant_id'), 'data_quality_assessments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_data_quality_assessments_workflow_instance_id'), 'data_quality_assessments', ['workflow_instance_id'], unique=False)
    op.create_table('feature_trials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('feature_name', sa.String(length=100), nullable=False),
    sa.Column('edition_required', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.Column('conversion_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_trials_expires', 'feature_trials', ['expires_at'], unique=False)
    op.create_index('idx_feature_trials_tenant', 'feature_trials', ['tenant_id'], unique=False)
    op.create_table('iam_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('agent_type', sa.Enum('workflow', 'adapter', 'service', 'monitor', 'scheduler', name='iamagenttype'), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'error', 'maintenance', name='iamagentstatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('health_status', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('license_cache',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('edition', sa.String(length=50), nullable=False),
    sa.Column('features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('limits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('cached_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_index('idx_license_cache_expires', 'license_cache', ['expires_at'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('api_key', sa.String(length=256), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('last_checked', sa.Float(), nullable=False),
    sa.Column('server_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('platform_adapters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('adapter_class', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('supported_auth_methods', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_beta', sa.Boolean(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('documentation_url', sa.String(length=500), nullable=True),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform')
    )
    op.create_index(op.f('ix_platform_adapters_id'), 'platform_adapters', ['id'], unique=False)
    op.create_table('platform_health',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('last_check_at', sa.DateTime(), nullable=False),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('uptime_percentage', sa.Integer(), nullable=True),
    sa.Column('total_checks', sa.Integer(), nullable=True),
    sa.Column('failed_checks', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('p95_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_health_id'), 'platform_health', ['id'], unique=False)
    op.create_index(op.f('ix_platform_health_platform'), 'platform_health', ['platform'], unique=False)
    op.create_table('quality_dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('edition_required', sa.String(length=20), nullable=False),
    sa.Column('measurement_method', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('quality_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_type', sa.String(length=50), nullable=True),
    sa.Column('applicable_dimensions', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('dimension_weights', sa.JSON(), nullable=True),
    sa.Column('thresholds', sa.JSON(), nullable=True),
    sa.Column('ml_model_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('edition_required', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_profiles_tenant', 'quality_profiles', ['tenant_id'], unique=False)
    op.create_index('idx_profiles_type', 'quality_profiles', ['profile_type'], unique=False)
    op.create_index(op.f('ix_quality_profiles_tenant_id'), 'quality_profiles', ['tenant_id'], unique=False)
    op.create_table('quality_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('rule_definition', sa.JSON(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('edition_required', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rules_active', 'quality_rules', ['is_active'], unique=False)
    op.create_index('idx_rules_dimension', 'quality_rules', ['dimension'], unique=False)
    op.create_index('idx_rules_tenant', 'quality_rules', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_quality_rules_tenant_id'), 'quality_rules', ['tenant_id'], unique=False)
    op.create_table('quality_slas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('dimension_targets', sa.JSON(), nullable=True),
    sa.Column('measurement_frequency', sa.String(length=50), nullable=True),
    sa.Column('alert_threshold', sa.Float(), nullable=True),
    sa.Column('escalation_rules', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sla_tenant', 'quality_slas', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_quality_slas_tenant_id'), 'quality_slas', ['tenant_id'], unique=False)
    op.create_table('quality_usage_tracking',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('feature', sa.String(length=100), nullable=False),
    sa.Column('edition', sa.String(length=20), nullable=False),
    sa.Column('usage_date', sa.DateTime(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_date', 'quality_usage_tracking', ['usage_date'], unique=False)
    op.create_index('idx_usage_tenant_date', 'quality_usage_tracking', ['tenant_id', 'usage_date'], unique=False)
    op.create_table('resource_pool_configs',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('min_size', sa.Integer(), nullable=False),
    sa.Column('max_size', sa.Integer(), nullable=False),
    sa.Column('acquire_timeout', sa.Float(), nullable=False),
    sa.Column('idle_timeout', sa.Float(), nullable=False),
    sa.Column('max_lifetime', sa.Float(), nullable=False),
    sa.Column('health_check_interval', sa.Float(), nullable=False),
    sa.Column('scale_up_threshold', sa.Float(), nullable=False),
    sa.Column('scale_down_threshold', sa.Float(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_monthly', sa.Float(), nullable=False),
    sa.Column('price_annual', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('limits', sa.JSON(), nullable=True),
    sa.Column('stripe_price_id_monthly', sa.String(), nullable=True),
    sa.Column('stripe_price_id_annual', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_subscription_plans_name', 'subscription_plans', ['name'], unique=False)
    op.create_table('tasks',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), server_default=sa.text("'default-tenant'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_table('tasks_mcp',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('destination', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('auto_escalated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('mcp_enabled', sa.Boolean(), nullable=False),
    sa.Column('mcp_metadata', sa.Text(), nullable=True),
    sa.Column('mcp_context_id', sa.String(length=36), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('tenant_limit_overrides',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('limit_type', sa.String(length=50), nullable=False),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.CheckConstraint('limit_value > 0', name='ck_positive_limit'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'limit_type', name='uq_tenant_limit_type')
    )
    op.create_table('upgrade_prompts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('prompt_type', sa.String(length=50), nullable=False),
    sa.Column('prompt_message', sa.Text(), nullable=False),
    sa.Column('target_edition', sa.String(length=50), nullable=True),
    sa.Column('shown_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('clicked', sa.Boolean(), nullable=False),
    sa.Column('converted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_upgrade_prompts_tenant', 'upgrade_prompts', ['tenant_id'], unique=False)
    op.create_index('idx_upgrade_prompts_type', 'upgrade_prompts', ['prompt_type'], unique=False)
    op.create_table('usage_limits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('edition', sa.String(), nullable=False),
    sa.Column('max_workflows', sa.Integer(), nullable=True),
    sa.Column('max_adapters', sa.Integer(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_api_calls_month', sa.Integer(), nullable=True),
    sa.Column('max_storage_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_metrics',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_metrics_tenant_metric', 'usage_metrics', ['tenant_id', 'metric_type'], unique=False)
    op.create_index('idx_usage_metrics_timestamp', 'usage_metrics', ['timestamp'], unique=False)
    op.create_table('usage_summaries',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('total_value', sa.DECIMAL(precision=20, scale=4), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('peak_value', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('percentile_95', sa.DECIMAL(precision=20, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'period_start', 'metric_type', name='uq_tenant_period_metric')
    )
    op.create_index('idx_usage_summaries_period', 'usage_summaries', ['period_start', 'period_end'], unique=False)
    op.create_index('idx_usage_summaries_tenant', 'usage_summaries', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('password_reset_token', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('email_verification_token', sa.String(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_backup_codes', sa.String(), nullable=True),
    sa.Column('mfa_enrolled_at', sa.DateTime(), nullable=True),
    sa.Column('mfa_last_used_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('workflow_definitions',
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), server_default=sa.text("'default-tenant'"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_tenant_id'), 'workflow_definitions', ['tenant_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_suffix', sa.String(length=10), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('key_salt', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('allowed_ips', sa.JSON(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(length=45), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_table('bridge_syncs',
    sa.Column('connection_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('items_created', sa.Integer(), nullable=True),
    sa.Column('items_updated', sa.Integer(), nullable=True),
    sa.Column('items_failed', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_options', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['bridge_connections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('iam_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('metric_type', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=50), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('metric_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['iam_agents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('agent_id', 'metric_type', 'period_start', name='uq_iam_metrics_period')
    )
    op.create_table('iam_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('initiator_id', sa.UUID(), nullable=False),
    sa.Column('session_type', sa.String(length=100), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('participants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_id'], ['iam_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_context_storage',
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('context_type', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('context_metadata', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks_mcp.task_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_server_capabilities',
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('capability', sa.String(length=50), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_tools',
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tool_schema', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('auth_method', sa.String(length=50), nullable=False),
    sa.Column('encrypted_data', sa.Text(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('execution_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_credentials_id'), 'platform_credentials', ['id'], unique=False)
    op.create_table('platform_webhooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('webhook_url', sa.String(length=500), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=False),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('successful_deliveries', sa.Integer(), nullable=True),
    sa.Column('failed_deliveries', sa.Integer(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_webhooks_id'), 'platform_webhooks', ['id'], unique=False)
    op.create_index(op.f('ix_platform_webhooks_platform'), 'platform_webhooks', ['platform'], unique=False)
    op.create_table('quality_improvements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assessment_id', sa.UUID(), nullable=True),
    sa.Column('improvement_type', sa.String(length=100), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=False),
    sa.Column('before_score', sa.Float(), nullable=True),
    sa.Column('after_score', sa.Float(), nullable=True),
    sa.Column('improvement_details', sa.JSON(), nullable=True),
    sa.Column('implemented_by', sa.UUID(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['data_quality_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_improvements_assessment', 'quality_improvements', ['assessment_id'], unique=False)
    op.create_index('idx_improvements_time', 'quality_improvements', ['implemented_at'], unique=False)
    op.create_index(op.f('ix_quality_improvements_implemented_at'), 'quality_improvements', ['implemented_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('plan_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIALING', 'PAST_DUE', 'CANCELED', 'EXPIRED', name='subscriptionstatus'), nullable=False),
    sa.Column('billing_period', sa.Enum('MONTHLY', 'ANNUAL', 'QUARTERLY', name='billingperiod'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=False),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['subscription_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_index('idx_subscriptions_stripe', 'subscriptions', ['stripe_subscription_id'], unique=False)
    op.create_index('idx_subscriptions_tenant', 'subscriptions', ['tenant_id'], unique=False)
    op.create_index('idx_subscriptions_user', 'subscriptions', ['user_id'], unique=False)
    op.create_table('webhooks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('auth_header', sa.String(length=255), nullable=True),
    sa.Column('auth_value_encrypted', sa.Text(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('max_retries', sa.Integer(), nullable=True),
    sa.Column('retry_delay_seconds', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), nullable=True),
    sa.Column('total_deliveries', sa.Integer(), nullable=True),
    sa.Column('total_failures', sa.Integer(), nullable=True),
    sa.Column('failure_threshold', sa.Integer(), nullable=True),
    sa.Column('disabled_reason', sa.String(length=500), nullable=True),
    sa.Column('custom_headers', sa.JSON(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_instances',
    sa.Column('definition_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', 'PAUSED', name='workflowstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), server_default=sa.text("'default-tenant'"), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_tenant_id'), 'workflow_instances', ['tenant_id'], unique=False)
    op.create_table('workflow_schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schedule_expression', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('input_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('next_run', sa.DateTime(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('edition', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('parent_template_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('definition_path', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('complexity', sa.Enum('simple', 'moderate', 'complex', 'advanced', name='workflow_complexity'), nullable=False),
    sa.Column('estimated_duration', sa.String(length=50), nullable=True),
    sa.Column('required_adapters', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('required_capabilities', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('rating', sa.DECIMAL(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_template_id'], ['workflow_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_templates_category', 'workflow_templates', ['category'], unique=False)
    op.create_index('idx_workflow_templates_owner', 'workflow_templates', ['owner_id'], unique=False)
    op.create_index('idx_workflow_templates_public', 'workflow_templates', ['is_public'], unique=False)
    op.create_index('idx_workflow_templates_system', 'workflow_templates', ['is_system'], unique=False)
    op.create_index('unique_system_template_name', 'workflow_templates', ['name'], unique=True, postgresql_where=sa.text('is_system = true'))
    op.create_table('workflow_triggers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_triggered', sa.DateTime(), nullable=True),
    sa.Column('trigger_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_key_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('api_key_id', sa.String(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('billing_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PAID', 'PENDING', 'FAILED', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(), nullable=False),
    sa.Column('billing_period_end', sa.DateTime(), nullable=False),
    sa.Column('stripe_invoice_id', sa.String(), nullable=True),
    sa.Column('stripe_charge_id', sa.String(), nullable=True),
    sa.Column('stripe_payment_intent_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_billing_history_period', 'billing_history', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_index('idx_billing_history_status', 'billing_history', ['status'], unique=False)
    op.create_index('idx_billing_history_subscription', 'billing_history', ['subscription_id'], unique=False)
    op.create_index('idx_billing_history_tenant', 'billing_history', ['tenant_id'], unique=False)
    op.create_index('idx_billing_history_user', 'billing_history', ['user_id'], unique=False)
    op.create_table('iam_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_type', sa.Enum('request', 'response', 'notification', 'broadcast', 'state_update', 'capability', 'error', 'heartbeat', name='iammessagetype'), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('recipient_id', sa.UUID(), nullable=True),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('correlation_id', sa.String(length=256), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'delivered', 'failed', 'expired', 'retrying', name='iammessagestatus'), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['iam_agents.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['iam_agents.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['iam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_invocations',
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=False),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['mcp_tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('last_four', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('exp_month', sa.Integer(), nullable=True),
    sa.Column('exp_year', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('stripe_payment_method_id', sa.String(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payment_methods_subscription', 'payment_methods', ['subscription_id'], unique=False)
    op.create_index('idx_payment_methods_tenant', 'payment_methods', ['tenant_id'], unique=False)
    op.create_index('idx_payment_methods_user', 'payment_methods', ['user_id'], unique=False)
    op.create_table('platform_executions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_id', sa.String(length=255), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('execution_id', sa.String(length=255), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('external_workflow_id', sa.String(length=255), nullable=False),
    sa.Column('external_execution_id', sa.String(length=255), nullable=True),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('estimated_cost', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['platform_credentials.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_executions_execution_id'), 'platform_executions', ['execution_id'], unique=False)
    op.create_index(op.f('ix_platform_executions_id'), 'platform_executions', ['id'], unique=False)
    op.create_index(op.f('ix_platform_executions_workflow_id'), 'platform_executions', ['workflow_id'], unique=False)
    op.create_table('platform_webhook_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('webhook_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('response_status', sa.Integer(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['platform_webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_webhook_deliveries_id'), 'platform_webhook_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_platform_webhook_deliveries_next_retry_at'), 'platform_webhook_deliveries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_platform_webhook_deliveries_webhook_id'), 'platform_webhook_deliveries', ['webhook_id'], unique=False)
    op.create_table('usage_tracking',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('subscription_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('billing_period_start', sa.DateTime(), nullable=True),
    sa.Column('billing_period_end', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usage_tracking_period', 'usage_tracking', ['billing_period_start', 'billing_period_end'], unique=False)
    op.create_index('idx_usage_tracking_resource', 'usage_tracking', ['resource_type'], unique=False)
    op.create_index('idx_usage_tracking_subscription', 'usage_tracking', ['subscription_id'], unique=False)
    op.create_index('idx_usage_tracking_tenant', 'usage_tracking', ['tenant_id'], unique=False)
    op.create_table('webhook_deliveries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('webhook_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_headers', sa.JSON(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['webhook_id'], ['webhooks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'running', 'paused', 'resuming', 'completed', 'failed', 'cancelled', name='workflow_execution_status'), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triggered_by', sa.String(length=100), nullable=True),
    sa.Column('trigger_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_steps',
    sa.Column('workflow_instance_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('step_name', sa.String(length=256), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED', name='stepstatus'), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), server_default=sa.text("'default-tenant'"), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['workflow_instance_id'], ['workflow_instances.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_steps_tenant_id'), 'workflow_steps', ['tenant_id'], unique=False)
    op.create_table('workflow_template_permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('permission', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.Column('granted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_permissions_template', 'workflow_template_permissions', ['template_id'], unique=False)
    op.create_index('idx_template_permissions_user', 'workflow_template_permissions', ['user_id'], unique=False)
    op.create_index('unique_user_template_permission', 'workflow_template_permissions', ['template_id', 'user_id', 'permission'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_table('workflow_template_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_reviews_template', 'workflow_template_reviews', ['template_id'], unique=False)
    op.create_index('idx_template_reviews_user', 'workflow_template_reviews', ['user_id'], unique=False)
    op.create_index('unique_user_template_review', 'workflow_template_reviews', ['template_id', 'user_id'], unique=True)
    op.create_table('workflow_template_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('instantiated_at', sa.DateTime(), nullable=False),
    sa.Column('customization_level', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_template_usage_date', 'workflow_template_usage', ['instantiated_at'], unique=False)
    op.create_index('idx_template_usage_template', 'workflow_template_usage', ['template_id'], unique=False)
    op.create_index('idx_template_usage_user', 'workflow_template_usage', ['user_id'], unique=False)
    op.create_table('iam_event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('event_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['iam_agents.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['iam_messages.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['iam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', 'cancelled', 'skipped', 'retry_required', 'requires_approval', name='node_execution_status'), nullable=False),
    sa.Column('inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_checkpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('execution_id', sa.UUID(), nullable=False),
    sa.Column('checkpoint_type', sa.String(length=50), nullable=False),
    sa.Column('state_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completed_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pending_nodes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('workflow_variables', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_checkpoints')
    op.drop_table('node_executions')
    op.drop_table('iam_event_logs')
    op.drop_index('idx_template_usage_user', table_name='workflow_template_usage')
    op.drop_index('idx_template_usage_template', table_name='workflow_template_usage')
    op.drop_index('idx_template_usage_date', table_name='workflow_template_usage')
    op.drop_table('workflow_template_usage')
    op.drop_index('unique_user_template_review', table_name='workflow_template_reviews')
    op.drop_index('idx_template_reviews_user', table_name='workflow_template_reviews')
    op.drop_index('idx_template_reviews_template', table_name='workflow_template_reviews')
    op.drop_table('workflow_template_reviews')
    op.drop_index('unique_user_template_permission', table_name='workflow_template_permissions', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_index('idx_template_permissions_user', table_name='workflow_template_permissions')
    op.drop_index('idx_template_permissions_template', table_name='workflow_template_permissions')
    op.drop_table('workflow_template_permissions')
    op.drop_index(op.f('ix_workflow_steps_tenant_id'), table_name='workflow_steps')
    op.drop_table('workflow_steps')
    op.drop_table('workflow_executions')
    op.drop_table('webhook_deliveries')
    op.drop_index('idx_usage_tracking_tenant', table_name='usage_tracking')
    op.drop_index('idx_usage_tracking_subscription', table_name='usage_tracking')
    op.drop_index('idx_usage_tracking_resource', table_name='usage_tracking')
    op.drop_index('idx_usage_tracking_period', table_name='usage_tracking')
    op.drop_table('usage_tracking')
    op.drop_index(op.f('ix_platform_webhook_deliveries_webhook_id'), table_name='platform_webhook_deliveries')
    op.drop_index(op.f('ix_platform_webhook_deliveries_next_retry_at'), table_name='platform_webhook_deliveries')
    op.drop_index(op.f('ix_platform_webhook_deliveries_id'), table_name='platform_webhook_deliveries')
    op.drop_table('platform_webhook_deliveries')
    op.drop_index(op.f('ix_platform_executions_workflow_id'), table_name='platform_executions')
    op.drop_index(op.f('ix_platform_executions_id'), table_name='platform_executions')
    op.drop_index(op.f('ix_platform_executions_execution_id'), table_name='platform_executions')
    op.drop_table('platform_executions')
    op.drop_index('idx_payment_methods_user', table_name='payment_methods')
    op.drop_index('idx_payment_methods_tenant', table_name='payment_methods')
    op.drop_index('idx_payment_methods_subscription', table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_table('mcp_invocations')
    op.drop_table('iam_messages')
    op.drop_index('idx_billing_history_user', table_name='billing_history')
    op.drop_index('idx_billing_history_tenant', table_name='billing_history')
    op.drop_index('idx_billing_history_subscription', table_name='billing_history')
    op.drop_index('idx_billing_history_status', table_name='billing_history')
    op.drop_index('idx_billing_history_period', table_name='billing_history')
    op.drop_table('billing_history')
    op.drop_table('api_key_logs')
    op.drop_table('workflow_triggers')
    op.drop_index('unique_system_template_name', table_name='workflow_templates', postgresql_where=sa.text('is_system = true'))
    op.drop_index('idx_workflow_templates_system', table_name='workflow_templates')
    op.drop_index('idx_workflow_templates_public', table_name='workflow_templates')
    op.drop_index('idx_workflow_templates_owner', table_name='workflow_templates')
    op.drop_index('idx_workflow_templates_category', table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_table('workflow_schedules')
    op.drop_index(op.f('ix_workflow_instances_tenant_id'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    op.drop_table('webhooks')
    op.drop_index('idx_subscriptions_user', table_name='subscriptions')
    op.drop_index('idx_subscriptions_tenant', table_name='subscriptions')
    op.drop_index('idx_subscriptions_stripe', table_name='subscriptions')
    op.drop_index('idx_subscriptions_status', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_quality_improvements_implemented_at'), table_name='quality_improvements')
    op.drop_index('idx_improvements_time', table_name='quality_improvements')
    op.drop_index('idx_improvements_assessment', table_name='quality_improvements')
    op.drop_table('quality_improvements')
    op.drop_index(op.f('ix_platform_webhooks_platform'), table_name='platform_webhooks')
    op.drop_index(op.f('ix_platform_webhooks_id'), table_name='platform_webhooks')
    op.drop_table('platform_webhooks')
    op.drop_index(op.f('ix_platform_credentials_id'), table_name='platform_credentials')
    op.drop_table('platform_credentials')
    op.drop_table('mcp_tools')
    op.drop_table('mcp_server_capabilities')
    op.drop_table('mcp_context_storage')
    op.drop_table('iam_sessions')
    op.drop_table('iam_metrics')
    op.drop_table('bridge_syncs')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_workflow_definitions_tenant_id'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_usage_summaries_tenant', table_name='usage_summaries')
    op.drop_index('idx_usage_summaries_period', table_name='usage_summaries')
    op.drop_table('usage_summaries')
    op.drop_index('idx_usage_metrics_timestamp', table_name='usage_metrics')
    op.drop_index('idx_usage_metrics_tenant_metric', table_name='usage_metrics')
    op.drop_table('usage_metrics')
    op.drop_table('usage_limits')
    op.drop_index('idx_upgrade_prompts_type', table_name='upgrade_prompts')
    op.drop_index('idx_upgrade_prompts_tenant', table_name='upgrade_prompts')
    op.drop_table('upgrade_prompts')
    op.drop_table('tenant_limit_overrides')
    op.drop_table('tasks_mcp')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_subscription_plans_name', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_table('resource_pool_configs')
    op.drop_index('idx_usage_tenant_date', table_name='quality_usage_tracking')
    op.drop_index('idx_usage_date', table_name='quality_usage_tracking')
    op.drop_table('quality_usage_tracking')
    op.drop_index(op.f('ix_quality_slas_tenant_id'), table_name='quality_slas')
    op.drop_index('idx_sla_tenant', table_name='quality_slas')
    op.drop_table('quality_slas')
    op.drop_index(op.f('ix_quality_rules_tenant_id'), table_name='quality_rules')
    op.drop_index('idx_rules_tenant', table_name='quality_rules')
    op.drop_index('idx_rules_dimension', table_name='quality_rules')
    op.drop_index('idx_rules_active', table_name='quality_rules')
    op.drop_table('quality_rules')
    op.drop_index(op.f('ix_quality_profiles_tenant_id'), table_name='quality_profiles')
    op.drop_index('idx_profiles_type', table_name='quality_profiles')
    op.drop_index('idx_profiles_tenant', table_name='quality_profiles')
    op.drop_table('quality_profiles')
    op.drop_table('quality_dimensions')
    op.drop_index(op.f('ix_platform_health_platform'), table_name='platform_health')
    op.drop_index(op.f('ix_platform_health_id'), table_name='platform_health')
    op.drop_table('platform_health')
    op.drop_index(op.f('ix_platform_adapters_id'), table_name='platform_adapters')
    op.drop_table('platform_adapters')
    op.drop_table('mcp_servers')
    op.drop_index('idx_license_cache_expires', table_name='license_cache')
    op.drop_table('license_cache')
    op.drop_table('iam_agents')
    op.drop_index('idx_feature_trials_tenant', table_name='feature_trials')
    op.drop_index('idx_feature_trials_expires', table_name='feature_trials')
    op.drop_table('feature_trials')
    op.drop_index(op.f('ix_data_quality_assessments_workflow_instance_id'), table_name='data_quality_assessments')
    op.drop_index(op.f('ix_data_quality_assessments_tenant_id'), table_name='data_quality_assessments')
    op.drop_index(op.f('ix_data_quality_assessments_assessment_time'), table_name='data_quality_assessments')
    op.drop_index('idx_quality_workflow', table_name='data_quality_assessments')
    op.drop_index('idx_quality_time', table_name='data_quality_assessments')
    op.drop_index('idx_quality_tenant', table_name='data_quality_assessments')
    op.drop_table('data_quality_assessments')
    op.drop_index(op.f('ix_data_lineage_workflow_instance_id'), table_name='data_lineage')
    op.drop_index(op.f('ix_data_lineage_timestamp'), table_name='data_lineage')
    op.drop_index('idx_lineage_workflow', table_name='data_lineage')
    op.drop_index('idx_lineage_time', table_name='data_lineage')
    op.drop_index('idx_lineage_nodes', table_name='data_lineage')
    op.drop_table('data_lineage')
    op.drop_table('bridge_connections')
    op.drop_index('idx_billing_events_type', table_name='billing_events')
    op.drop_index('idx_billing_events_tenant', table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index('idx_usage_tenant_period', table_name='basic_usage_metrics')
    op.drop_table('basic_usage_metrics')
    op.drop_table('adapters')
    # ### end Alembic commands ###