"""add_oauth2_provider_id_to_mcp_servers

Revision ID: 2bc046024965
Revises: 956cdb4f437c
Create Date: 2025-11-30 05:09:02.875330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc046024965'
down_revision = '956cdb4f437c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = [col['name'] for col in inspector.get_columns('mcp_servers')]

    if 'oauth2_provider_id' not in existing_columns:
        op.add_column('mcp_servers', sa.Column('oauth2_provider_id', sa.String(length=36), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mcp_servers', 'oauth2_provider_id')
    # ### end Alembic commands ###