"""add_mcp_standard_fields

Revision ID: 331772706ff0
Revises: afe9a55a7388
Create Date: 2025-11-30 03:06:07.204809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331772706ff0'
down_revision = 'afe9a55a7388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_columns = [col['name'] for col in inspector.get_columns('mcp_servers')]

    columns_to_add = {
        'transport_type': sa.Column('transport_type', sa.String(length=20), server_default=sa.text("'stdio'"), nullable=False),
        'command': sa.Column('command', sa.String(length=256), nullable=True),
        'args': sa.Column('args', sa.Text(), nullable=True),
        'env_vars': sa.Column('env_vars', sa.Text(), nullable=True),
        'protocol_version': sa.Column('protocol_version', sa.String(length=20), nullable=True),
        'server_capabilities': sa.Column('server_capabilities', sa.Text(), nullable=True),
    }

    for col_name, col_def in columns_to_add.items():
        if col_name not in existing_columns:
            op.add_column('mcp_servers', col_def)

    # Check if url column is already nullable
    for col in inspector.get_columns('mcp_servers'):
        if col['name'] == 'url' and not col['nullable']:
            op.alter_column('mcp_servers', 'url',
                       existing_type=sa.VARCHAR(length=256),
                       nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('mcp_servers', 'server_capabilities')
    op.drop_column('mcp_servers', 'protocol_version')
    op.drop_column('mcp_servers', 'env_vars')
    op.drop_column('mcp_servers', 'args')
    op.drop_column('mcp_servers', 'command')
    op.drop_column('mcp_servers', 'transport_type')
    # ### end Alembic commands ###