"""add_mcp_standard_fields

Revision ID: 331772706ff0
Revises: afe9a55a7388
Create Date: 2025-11-30 03:06:07.204809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331772706ff0'
down_revision = 'afe9a55a7388'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mcp_servers', sa.Column('transport_type', sa.String(length=20), server_default=sa.text("'stdio'"), nullable=False))
    op.add_column('mcp_servers', sa.Column('command', sa.String(length=256), nullable=True))
    op.add_column('mcp_servers', sa.Column('args', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('env_vars', sa.Text(), nullable=True))
    op.add_column('mcp_servers', sa.Column('protocol_version', sa.String(length=20), nullable=True))
    op.add_column('mcp_servers', sa.Column('server_capabilities', sa.Text(), nullable=True))
    op.alter_column('mcp_servers', 'url',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mcp_servers', 'url',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    op.drop_column('mcp_servers', 'server_capabilities')
    op.drop_column('mcp_servers', 'protocol_version')
    op.drop_column('mcp_servers', 'env_vars')
    op.drop_column('mcp_servers', 'args')
    op.drop_column('mcp_servers', 'command')
    op.drop_column('mcp_servers', 'transport_type')
    # ### end Alembic commands ###