"""add_adapter_configs_table_fixed_fk

Revision ID: 43ec3e926d2e
Revises: bcaecda2ca36
Create Date: 2025-09-10 17:21:48.512705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ec3e926d2e'
down_revision = 'bcaecda2ca36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if table already exists before creating
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    if 'adapter_configs' in existing_tables:
        print("adapter_configs table already exists, skipping creation...")
        return

    op.create_table('adapter_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('adapter_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('credentials', sa.JSON(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('test_status', sa.String(length=50), nullable=True),
    sa.Column('test_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'adapter_type', 'name', name='_user_adapter_name_uc')
    )
    op.create_index(op.f('ix_adapter_configs_adapter_type'), 'adapter_configs', ['adapter_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_adapter_configs_adapter_type'), table_name='adapter_configs')
    op.drop_table('adapter_configs')
    # ### end Alembic commands ###