"""add_multi_tier_pattern_learning

Revision ID: 71644546b9dd
Revises: b2da379fcfc4
Create Date: 2025-10-28 00:27:30.333975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71644546b9dd'
down_revision = 'b2da379fcfc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learned_patterns', sa.Column('scope', sa.String(length=20), nullable=False, server_default='user'))
    op.add_column('learned_patterns', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('learned_patterns', sa.Column('organization_id', sa.UUID(), nullable=True))
    op.add_column('learned_patterns', sa.Column('promoted_from_scope', sa.String(length=20), nullable=True))
    op.add_column('learned_patterns', sa.Column('contributing_users_count', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('learned_patterns', sa.Column('promotion_candidate', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('learned_patterns', sa.Column('is_shareable', sa.Boolean(), nullable=False, server_default='true'))
    op.add_column('learned_patterns', sa.Column('contains_sensitive_data', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('learned_patterns', sa.Column('anonymized', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index('idx_pattern_promotion', 'learned_patterns', ['promotion_candidate', 'scope'], unique=False)
    op.create_index('idx_pattern_scope', 'learned_patterns', ['scope', 'user_id', 'organization_id'], unique=False)
    op.create_index(op.f('ix_learned_patterns_organization_id'), 'learned_patterns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_learned_patterns_user_id'), 'learned_patterns', ['user_id'], unique=False)
    op.create_foreign_key(None, 'learned_patterns', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'learned_patterns', type_='foreignkey')
    op.drop_index(op.f('ix_learned_patterns_user_id'), table_name='learned_patterns')
    op.drop_index(op.f('ix_learned_patterns_organization_id'), table_name='learned_patterns')
    op.drop_index('idx_pattern_scope', table_name='learned_patterns')
    op.drop_index('idx_pattern_promotion', table_name='learned_patterns')
    op.drop_column('learned_patterns', 'anonymized')
    op.drop_column('learned_patterns', 'contains_sensitive_data')
    op.drop_column('learned_patterns', 'is_shareable')
    op.drop_column('learned_patterns', 'promotion_candidate')
    op.drop_column('learned_patterns', 'contributing_users_count')
    op.drop_column('learned_patterns', 'promoted_from_scope')
    op.drop_column('learned_patterns', 'organization_id')
    op.drop_column('learned_patterns', 'user_id')
    op.drop_column('learned_patterns', 'scope')
    # ### end Alembic commands ###