"""add_mcp_async_tasks_table

Revision ID: 956cdb4f437c
Revises: 331772706ff0
Create Date: 2025-11-30 04:43:55.502565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956cdb4f437c'
down_revision = '331772706ff0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    if 'mcp_async_tasks' not in existing_tables:
        op.create_table('mcp_async_tasks',
        sa.Column('server_id', sa.String(length=36), nullable=False),
        sa.Column('tool_id', sa.String(length=36), nullable=True),
        sa.Column('task_token', sa.String(length=256), nullable=False),
        sa.Column('method', sa.String(length=100), nullable=False),
        sa.Column('state', sa.Enum('WORKING', 'COMPLETED', 'FAILED', 'CANCELLED', name='mcptaskstate'), nullable=False),
        sa.Column('progress', sa.Integer(), nullable=True),
        sa.Column('progress_message', sa.String(length=512), nullable=True),
        sa.Column('request_params', sa.JSON(), nullable=True),
        sa.Column('result_content', sa.JSON(), nullable=True),
        sa.Column('structured_result', sa.JSON(), nullable=True),
        sa.Column('error_code', sa.Integer(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('error_data', sa.JSON(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('last_activity_at', sa.DateTime(), nullable=True),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('client_id', sa.String(length=256), nullable=True),
        sa.Column('task_metadata', sa.JSON(), nullable=True),
        sa.Column('id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
        sa.ForeignKeyConstraint(['tool_id'], ['mcp_tools.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('task_token')
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mcp_async_tasks')
    # ### end Alembic commands ###