"""add_user_id_to_workflow_executions

Revision ID: afe9a55a7388
Revises: fe95da50f057
Create Date: 2025-11-18 02:24:41.500481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe9a55a7388'
down_revision = 'fe95da50f057'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow_executions', sa.Column('user_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_executions', 'user_id')
    # ### end Alembic commands ###