"""create_conversation_system_tables

Revision ID: bcaecda2ca36
Revises: f321e1606465
Create Date: 2025-08-29 05:17:59.670742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcaecda2ca36'
down_revision = 'f321e1606465'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###