"""add_conversation_tables

Revision ID: f321e1606465
Revises: 076a5b5c57a8
Create Date: 2025-08-29 05:16:50.326928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f321e1606465'
down_revision = '076a5b5c57a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###