"""add_conversation_name_column

Revision ID: fe95da50f057
Revises: 74a61b3b83a4
Create Date: 2025-11-13 21:24:48.459534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe95da50f057'
down_revision = '74a61b3b83a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    existing_tables = inspector.get_table_names()

    if 'conversation_sessions' not in existing_tables:
        return

    existing_columns = [col['name'] for col in inspector.get_columns('conversation_sessions')]
    if 'name' not in existing_columns:
        op.add_column('conversation_sessions', sa.Column('name', sa.String(length=200), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'name')
    # ### end Alembic commands ###