"""add_conversation_name_column

Revision ID: fe95da50f057
Revises: 74a61b3b83a4
Create Date: 2025-11-13 21:24:48.459534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe95da50f057'
down_revision = '74a61b3b83a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversation_sessions', sa.Column('name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversation_sessions', 'name')
    # ### end Alembic commands ###