"""Pydantic schemas for AICtrlNet FastAPI."""

from .task import (
    TaskCreate,
    TaskUpdate,
    TaskResponse,
    TaskListResponse,
)

from .workflow import (
    WorkflowCreate,
    WorkflowUpdate,
    WorkflowResponse,
    WorkflowListResponse,
    WorkflowStepResponse,
)

# Legacy template schemas removed - functionality moved to workflow_templates

from .common import (
    PaginationResponse,
    ErrorResponse,
    SuccessResponse,
    HealthResponse,
)

from .ai_governance import (
    RiskLevel,
    QualityStandard,
    RiskAssessmentRequest,
    RiskAssessmentResponse,
    BatchRiskAssessmentRequest,
    BatchRiskAssessmentResponse,
    QualityVerificationRequest,
    QualityVerificationResponse,
    GovernanceOptimizationRequest,
    GovernanceOptimizationResponse,
    ApplyOptimizationRequest,
    ApplyOptimizationResponse,
    AIGovernanceMetrics,
    ModelTrainingRequest,
    ModelTrainingStatus,
)

from .api_key import (
    APIKeyCreate,
    APIKeyResponse,
    APIKeyCreateResponse,
    APIKeyUpdate,
    APIKeyListResponse,
    APIKeyRevoke,
    APIKeyVerifyRequest,
    APIKeyVerifyResponse,
)

from .webhook import (
    WebhookCreate,
    WebhookResponse,
    WebhookCreateResponse,
    WebhookUpdate,
    WebhookListResponse,
    WebhookTestRequest,
    WebhookTestResponse,
    WebhookDeliveryResponse,
    WebhookDeliveryListResponse,
    WebhookSignatureInfo,
)

from .data_quality import (
    QualityDimension,
    QualityDimensionInfo,
    AssessmentRequest,
    AssessmentResponse,
    RuleCreate,
    RuleResponse,
    ProfileCreate,
    ProfileResponse,
    SLACreate,
    SLAResponse,
    QualityMetrics,
    UsageSummary,
    LineageResponse,
    ComplianceReport,
)

from .data_quality_models import (
    DataQualityAssessmentBase,
    DataQualityAssessmentCreate,
    DataQualityAssessmentResponse,
    QualityRuleBase,
    QualityRuleCreate,
    QualityRuleResponse,
    QualityProfileBase,
    QualityProfileCreate,
    QualityProfileResponse,
    QualityImprovementBase,
    QualityImprovementCreate,
    QualityImprovementResponse,
    DataLineageBase,
    DataLineageCreate,
    DataLineageResponse,
    QualitySLABase,
    QualitySLACreate,
    QualitySLAResponse,
    QualityUsageTrackingBase,
    QualityUsageTrackingCreate,
    QualityUsageTrackingResponse,
)

from .audit import (
    AuditActionType,
    AuditSeverity,
    AuditLogBase,
    AuditLogCreate,
    AuditLogResponse,
    AuditLogQuery,
    AuditLogList,
    AuditFilterBase,
    AuditFilterCreate,
    AuditFilterUpdate,
    AuditFilterResponse,
    AuditFilterList,
    AuditSummary,
    AuditExportBase,
    AuditExportCreate,
    AuditExportResponse,
    AuditActionInfo,
    AuditSeverityInfo,
    AuditResourceTypeList,
    AuditCleanupRequest,
    AuditCleanupResponse,
    AuditHealthResponse,
)

from .license import (
    SubscriptionStatus,
    BillingPeriod,
    FeatureStatus,
    SubscriptionStatusResponse,
    UsageSummaryResponse,
    UsageLimitResponse,
    UsageLimitsList,
    FeatureAvailability,
    FeaturesList,
    UpgradeOption,
    UpgradeOptionsList,
    TrialActivationRequest,
    TrialActivationResponse,
    TrialStatusResponse,
    BillingHistoryItem,
    BillingHistoryResponse,
    CostBreakdown,
    CostEstimateResponse,
    LicenseHealthResponse,
)

from .geographic import (
    RegionStatus,
    RoutingPolicy,
    GeographicRegionBase,
    GeographicRegionCreate,
    GeographicRegionUpdate,
    GeographicRegionResponse,
    GeographicRegionList,
    RoutingRuleBase,
    RoutingRuleCreate,
    RoutingRuleUpdate,
    RoutingRuleResponse,
    RoutingRuleList,
    RegionHealthMetricBase,
    RegionHealthMetricCreate,
    RegionHealthMetricResponse,
    RegionHealthList,
    TrafficRouteBase,
    TrafficRouteCreate,
    TrafficRouteResponse,
    TrafficSummary,
    RouteRequest,
    RouteResponse,
    RegionConfigurationBase,
    RegionConfigurationCreate,
    RegionConfigurationUpdate,
    RegionConfigurationResponse,
    DistanceResponse,
    PolicyInfo,
    StatusInfo,
)

from .mcp import (
    MCPServerCreate,
    MCPServerResponse,
    MCPServerUpdate,
    MCPContextCreate,
    MCPContextResponse,
    MCPCapability,
    MCPExecuteRequest,
    MCPExecuteResponse,
    MCPDiscoveryResponse,
    MCPInfo,
)

from .mfa import (
    MFAInitRequest,
    MFACompleteRequest,
    MFAVerifyRequest,
    MFADisableRequest,
    MFAResetRequest,
    MFAStatusResponse,
    MFAInitResponse,
    MFACompleteResponse,
    MFAVerifyResponse,
    MFADisableResponse,
    MFADeviceResponse,
    MFARecoveryCodesResponse,
    LoginRequest,
    LoginResponse,
)

from .workflow_templates import (
    TemplateComplexity,
    TemplatePermission,
    CustomizationLevel,
    TemplateParameterType,
    TemplateParameter,
    WorkflowTemplateBase,
    WorkflowTemplateCreate,
    WorkflowTemplateUpdate,
    WorkflowTemplateResponse,
    WorkflowTemplateDetail,
    TemplatePermissionCreate,
    TemplatePermissionResponse,
    TemplateUsageCreate,
    TemplateUsageResponse,
    TemplateReviewCreate,
    TemplateReviewUpdate,
    TemplateReviewResponse,
    InstantiateTemplateRequest,
    InstantiateTemplateResponse,
    ForkTemplateRequest,
    TemplateListRequest,
    TemplateListResponse,
    TemplateAnalyticsResponse,
    WorkflowFromTemplate,  # Moved from old template schemas
)

# Extended schemas for missing models
from .subscription_extended import (
    UsageTrackingBase,
    UsageTrackingCreate,
    UsageTrackingUpdate,
    UsageTrackingResponse,
    PaymentMethodBase,
    PaymentMethodCreate,
    PaymentMethodUpdate,
    PaymentMethodResponse,
    BillingHistoryBase,
    BillingHistoryCreate,
    BillingHistoryUpdate,
    BillingHistoryResponse,
    BillingEventBase,
    BillingEventCreate,
    BillingEventResponse,
)

from .iam_extended import (
    IAMEventLogBase,
    IAMEventLogCreate,
    IAMEventLogResponse,
    IAMMetricBase,
    IAMMetricCreate,
    IAMMetricResponse,
    TenantLimitOverrideBase,
    TenantLimitOverrideCreate,
    TenantLimitOverrideResponse,
    FeatureTrialBase,
    FeatureTrialCreate,
    FeatureTrialResponse,
    LicenseCacheBase,
    LicenseCacheCreate,
    LicenseCacheResponse,
    PlatformWebhookDeliveryBase,
    PlatformWebhookDeliveryCreate,
    PlatformWebhookDeliveryResponse,
    APIKeyLogBase,
    APIKeyLogCreate,
    APIKeyLogResponse,
)

from .mcp_extended import (
    MCPServerCapabilityBase,
    MCPServerCapabilityCreate,
    MCPServerCapabilityUpdate,
    MCPServerCapabilityResponse,
    TaskMCPBase,
    TaskMCPCreate,
    TaskMCPUpdate,
    TaskMCPResponse,
    MCPContextStorageBase,
    MCPContextStorageCreate,
    MCPContextStorageUpdate,
    MCPContextStorageResponse,
    MCPToolBase,
    MCPToolCreate,
    MCPToolUpdate,
    MCPToolResponse,
    MCPInvocationBase,
    MCPInvocationCreate,
    MCPInvocationUpdate,
    MCPInvocationResponse,
)

from .workflow_extended import (
    WorkflowDefinitionBase,
    WorkflowDefinitionCreate,
    WorkflowDefinitionResponse,
    WorkflowTemplatePermissionBase,
    WorkflowTemplatePermissionCreate,
    WorkflowTemplatePermissionResponse,
    WorkflowTemplateUsageBase,
    WorkflowTemplateUsageCreate,
    WorkflowTemplateUsageResponse,
    WorkflowTemplateReviewBase,
    WorkflowTemplateReviewCreate,
    WorkflowTemplateReviewResponse,
    BridgeConnectionBase,
    BridgeConnectionCreate,
    BridgeConnectionResponse,
    BridgeSyncBase,
    BridgeSyncCreate,
    BridgeSyncResponse,
    QualityDimensionModelBase,
    QualityDimensionModelCreate,
    QualityDimensionModelUpdate,
    QualityDimensionModelResponse,
)

from .knowledge import (
    KnowledgeItemBase,
    KnowledgeItemCreate,
    KnowledgeItemUpdate,
    KnowledgeItemResponse,
    KnowledgeQueryCreate,
    KnowledgeQueryResponse,
    SystemManifestResponse,
    KnowledgeRetrievalRequest,
    KnowledgeRetrievalResponse,
    KnowledgeSearchRequest,
    KnowledgeSearchResponse,
    SuggestionRequest,
    SuggestionItem,
    SuggestionResponse,
    LearnedPatternResponse,
    CapabilitySummaryResponse,
    FeatureDetailResponse,
    KnowledgeStatsResponse,
)

from .incomplete_fixes import (
    # Complete subscription schemas
    SubscriptionPlanBase,
    SubscriptionPlanCreate,
    SubscriptionPlanUpdate,
    SubscriptionBase,
    # Update schemas for incomplete models
    IAMMessageUpdate,
    IAMEventLogUpdate,
    IAMMetricUpdate,
    TenantLimitOverrideUpdate,
    FeatureTrialUpdate,
    LicenseCacheUpdate,
    PlatformWebhookDeliveryUpdate,
    APIKeyLogUpdate,
    WorkflowDefinitionUpdate,
    MCPServerCapabilityUpdate,
    MCPInvocationUpdate,
    MCPServerBase,
    MCPServerCreate,
    MCPServerUpdate,
    MCPToolUpdate,
    MCPContextStorageUpdate,
    BridgeConnectionUpdate,
    BridgeSyncUpdate,
    WorkflowTemplateUsageUpdate,
    WorkflowTemplatePermissionUpdate,
    WorkflowTemplateReviewUpdate,
    UsageTrackingUpdate,
    PaymentMethodUpdate,
    BillingHistoryUpdate,
    BillingEventUpdate,
    # Remaining complete schemas
    WebhookBase,
    WebhookDeliveryBase,
    WebhookDeliveryCreate,
    WebhookDeliveryUpdate,
    UsageMetricBase,
    UsageMetricCreate,
    UsageMetricUpdate,
    UpgradePromptBase,
    UpgradePromptCreate,
    UpgradePromptUpdate,
    UsageSummaryBase,
    UsageSummaryCreate,
    UsageSummaryUpdate,
    # Workflow execution schemas
    WorkflowExecutionBase,
    NodeExecutionBase,
    NodeExecutionCreate,
    WorkflowCheckpointBase,
    WorkflowCheckpointUpdate,
    WorkflowTriggerBase,
    WorkflowScheduleBase,
)

__all__ = [
    # Task schemas
    "TaskCreate",
    "TaskUpdate",
    "TaskResponse",
    "TaskListResponse",
    # Workflow schemas
    "WorkflowCreate",
    "WorkflowUpdate",
    "WorkflowResponse",
    "WorkflowListResponse",
    "WorkflowStepResponse",
    "WorkflowFromTemplate",
    # Legacy template schemas (removed)
    # "TemplateResponse",
    # "TemplateListResponse",
    # Common schemas
    "PaginationResponse",
    "ErrorResponse",
    "SuccessResponse",
    "HealthResponse",
    # AI Governance schemas
    "RiskLevel",
    "QualityStandard",
    "RiskAssessmentRequest",
    "RiskAssessmentResponse",
    "BatchRiskAssessmentRequest",
    "BatchRiskAssessmentResponse",
    "QualityVerificationRequest",
    "QualityVerificationResponse",
    "GovernanceOptimizationRequest",
    "GovernanceOptimizationResponse",
    "ApplyOptimizationRequest",
    "ApplyOptimizationResponse",
    "AIGovernanceMetrics",
    "ModelTrainingRequest",
    "ModelTrainingStatus",
    # Data Quality schemas
    "QualityDimension",
    "QualityDimensionInfo",
    "AssessmentRequest",
    "AssessmentResponse",
    "RuleCreate",
    "RuleResponse",
    "ProfileCreate",
    "ProfileResponse",
    "SLACreate",
    "SLAResponse",
    "QualityMetrics",
    "UsageSummary",
    "LineageResponse",
    "ComplianceReport",
    # Data Quality Model schemas
    "DataQualityAssessmentBase",
    "DataQualityAssessmentCreate",
    "DataQualityAssessmentResponse",
    "QualityRuleBase",
    "QualityRuleCreate",
    "QualityRuleResponse",
    "QualityProfileBase",
    "QualityProfileCreate",
    "QualityProfileResponse",
    "QualityImprovementBase",
    "QualityImprovementCreate",
    "QualityImprovementResponse",
    "DataLineageBase",
    "DataLineageCreate",
    "DataLineageResponse",
    "QualitySLABase",
    "QualitySLACreate",
    "QualitySLAResponse",
    "QualityUsageTrackingBase",
    "QualityUsageTrackingCreate",
    "QualityUsageTrackingResponse",
    # API Key schemas
    "APIKeyCreate",
    "APIKeyResponse",
    "APIKeyCreateResponse",
    "APIKeyUpdate",
    "APIKeyListResponse",
    "APIKeyRevoke",
    "APIKeyVerifyRequest",
    "APIKeyVerifyResponse",
    # Webhook schemas
    "WebhookCreate",
    "WebhookResponse",
    "WebhookCreateResponse",
    "WebhookUpdate",
    "WebhookListResponse",
    "WebhookTestRequest",
    "WebhookTestResponse",
    "WebhookDeliveryResponse",
    "WebhookDeliveryListResponse",
    "WebhookSignatureInfo",
    # Audit schemas
    "AuditActionType",
    "AuditSeverity",
    "AuditLogBase",
    "AuditLogCreate",
    "AuditLogResponse",
    "AuditLogQuery",
    "AuditLogList",
    "AuditFilterBase",
    "AuditFilterCreate",
    "AuditFilterUpdate",
    "AuditFilterResponse",
    "AuditFilterList",
    "AuditSummary",
    "AuditExportBase",
    "AuditExportCreate",
    "AuditExportResponse",
    "AuditActionInfo",
    "AuditSeverityInfo",
    "AuditResourceTypeList",
    "AuditCleanupRequest",
    "AuditCleanupResponse",
    "AuditHealthResponse",
    # License schemas
    "SubscriptionStatus",
    "BillingPeriod",
    "FeatureStatus",
    "SubscriptionStatusResponse",
    "UsageSummaryResponse",
    "UsageLimitResponse",
    "UsageLimitsList",
    "FeatureAvailability",
    "FeaturesList",
    "UpgradeOption",
    "UpgradeOptionsList",
    "TrialActivationRequest",
    "TrialActivationResponse",
    "TrialStatusResponse",
    "BillingHistoryItem",
    "BillingHistoryResponse",
    "CostBreakdown",
    "CostEstimateResponse",
    "LicenseHealthResponse",
    # Geographic schemas
    "RegionStatus",
    "RoutingPolicy",
    "GeographicRegionBase",
    "GeographicRegionCreate",
    "GeographicRegionUpdate",
    "GeographicRegionResponse",
    "GeographicRegionList",
    "RoutingRuleBase",
    "RoutingRuleCreate",
    "RoutingRuleUpdate",
    "RoutingRuleResponse",
    "RoutingRuleList",
    "RegionHealthMetricBase",
    "RegionHealthMetricCreate",
    "RegionHealthMetricResponse",
    "RegionHealthList",
    "TrafficRouteBase",
    "TrafficRouteCreate",
    "TrafficRouteResponse",
    "TrafficSummary",
    "RouteRequest",
    "RouteResponse",
    "RegionConfigurationBase",
    "RegionConfigurationCreate",
    "RegionConfigurationUpdate",
    "RegionConfigurationResponse",
    "DistanceResponse",
    "PolicyInfo",
    "StatusInfo",
    # MCP schemas
    "MCPServerCreate",
    "MCPServerResponse",
    "MCPServerUpdate",
    "MCPContextCreate",
    "MCPContextResponse",
    "MCPCapability",
    "MCPExecuteRequest",
    "MCPExecuteResponse",
    "MCPDiscoveryResponse",
    "MCPInfo",
    # MFA schemas
    "MFAInitRequest",
    "MFACompleteRequest",
    "MFAVerifyRequest",
    "MFADisableRequest",
    "MFAResetRequest",
    "MFAStatusResponse",
    "MFAInitResponse",
    "MFACompleteResponse",
    "MFAVerifyResponse",
    "MFADisableResponse",
    "MFADeviceResponse",
    "MFARecoveryCodesResponse",
    "LoginRequest",
    "LoginResponse",
    # Workflow Template schemas
    "TemplateComplexity",
    "TemplatePermission",
    "CustomizationLevel",
    "TemplateParameterType",
    "TemplateParameter",
    "WorkflowTemplateBase",
    "WorkflowTemplateCreate",
    "WorkflowTemplateUpdate",
    "WorkflowTemplateResponse",
    "WorkflowTemplateDetail",
    "TemplatePermissionCreate",
    "TemplatePermissionResponse",
    "TemplateUsageCreate",
    "TemplateUsageResponse",
    "TemplateReviewCreate",
    "TemplateReviewUpdate",
    "TemplateReviewResponse",
    "InstantiateTemplateRequest",
    "InstantiateTemplateResponse",
    "ForkTemplateRequest",
    "TemplateListRequest",
    "TemplateListResponse",
    "TemplateAnalyticsResponse",
    # Completed missing schemas
    "SubscriptionPlanBase",
    "SubscriptionPlanCreate",
    "SubscriptionPlanUpdate",
    "SubscriptionBase",
    "IAMMessageUpdate",
    "IAMEventLogUpdate",
    "IAMMetricUpdate",
    "TenantLimitOverrideUpdate",
    "FeatureTrialUpdate",
    "LicenseCacheUpdate",
    "PlatformWebhookDeliveryUpdate",
    "APIKeyLogUpdate",
    "WorkflowDefinitionUpdate",
    "MCPServerCapabilityUpdate",
    "MCPInvocationUpdate",
    "MCPServerBase",
    "MCPServerCreate",
    "MCPServerUpdate",
    "MCPToolUpdate",
    "MCPContextStorageUpdate",
    "BridgeConnectionUpdate",
    "BridgeSyncUpdate",
    "WorkflowTemplateUsageUpdate",
    "WorkflowTemplatePermissionUpdate",
    "WorkflowTemplateReviewUpdate",
    "UsageTrackingUpdate",
    "PaymentMethodUpdate",
    "BillingHistoryUpdate",
    "BillingEventUpdate",
    "WebhookBase",
    "WebhookDeliveryBase",
    "WebhookDeliveryCreate",
    "WebhookDeliveryUpdate",
    "UsageMetricBase",
    "UsageMetricCreate",
    "UsageMetricUpdate",
    "UpgradePromptBase",
    "UpgradePromptCreate",
    "UpgradePromptUpdate",
    "UsageSummaryBase",
    "UsageSummaryCreate",
    "UsageSummaryUpdate",
    "WorkflowExecutionBase",
    "NodeExecutionBase",
    "NodeExecutionCreate",
    "WorkflowCheckpointBase",
    "WorkflowCheckpointUpdate",
    "WorkflowTriggerBase",
    "WorkflowScheduleBase",
    # Knowledge schemas
    "KnowledgeItemBase",
    "KnowledgeItemCreate",
    "KnowledgeItemUpdate",
    "KnowledgeItemResponse",
    "KnowledgeQueryCreate",
    "KnowledgeQueryResponse",
    "SystemManifestResponse",
    "KnowledgeRetrievalRequest",
    "KnowledgeRetrievalResponse",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResponse",
    "SuggestionRequest",
    "SuggestionItem",
    "SuggestionResponse",
    "LearnedPatternResponse",
    "CapabilitySummaryResponse",
    "FeatureDetailResponse",
    "KnowledgeStatsResponse",
]